/**
 * Doc Shield — L1 scanner test suite.
 *
 * Runs the shipping scanner sources (copied verbatim into .build/ by prepare.mjs)
 * against hand-built malicious and benign fixtures, and asserts on the finding
 * ids each case must produce. Fixtures are generated by make_fixtures.py, which
 * writes hostile metadata directly rather than going through a zip library —
 * a zip bomb is defined by what it *declares*, not by what it contains.
 */

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

import { ThreatScanner } from './.build/services/ThreatScanner.ts';
import { HashBlacklist } from './.build/services/scanners/HashBlacklist.ts';
import { sha256Hex } from './.build/services/scanners/Sha256.ts';
import { analyzePe } from './.build/services/scanners/PEAnalyzer.ts';
import { containsAlias, precheck } from './.build/services/scanners/RequirementKeywords.ts';
import {
  checkFormats,
  extractNamingRule,
  parseRequirement
} from './.build/services/scanners/RequirementKeywords.ts';
import { checkNaming, parseNamingTemplate } from './.build/services/scanners/NamingTemplate.ts';
import {
  auditRequirement,
  describeLocalRequirements,
  scoreForFindings
} from './.build/services/RequirementAudit.ts';

const here = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES = path.join(here, 'fixtures');

let passed = 0;
let failed = 0;
const failures = [];

function load(name) {
  return new Uint8Array(fs.readFileSync(path.join(FIXTURES, name)));
}

function check(label, condition, detail) {
  if (condition) {
    passed++;
  } else {
    failed++;
    failures.push(`${label}${detail ? ` — ${detail}` : ''}`);
  }
}

function ids(report) {
  return report.findings.map((finding) => finding.id);
}

function levelOf(report, id) {
  const finding = report.findings.find((item) => item.id === id);
  return finding ? finding.level : undefined;
}

/**
 * @param {string} fixture
 * @param {object} spec
 * @param {string[]} [spec.mustHave]
 * @param {string[]} [spec.mustNotHave]
 * @param {string}   [spec.verdict]
 * @param {number}   [spec.scoreBelow]
 * @param {number}   [spec.scoreAbove]
 * @param {string}   [spec.expectLevel]  `id=level` pair for a mandatory level
 */
function scenario(fixture, spec) {
  const name = fixture;
  const data = load(fixture);
  const report = ThreatScanner.scanFile(fixture, data, { blacklist: BLACKLIST });

  const present = ids(report);

  for (const id of spec.mustHave ?? []) {
    check(
      `${name} 必须命中 ${id}`,
      present.includes(id),
      `实际命中: ${present.join(', ') || '(无)'}`
    );
  }
  for (const id of spec.mustNotHave ?? []) {
    check(
      `${name} 不应命中 ${id}`,
      !present.includes(id),
      `实际命中: ${present.join(', ')}`
    );
  }
  if (spec.verdict) {
    check(
      `${name} 判定应为 ${spec.verdict}`,
      report.verdict === spec.verdict,
      `实际 ${report.verdict}（score ${report.score}）`
    );
  }
  if (spec.scoreBelow !== undefined) {
    check(
      `${name} 分数应低于 ${spec.scoreBelow}`,
      report.score < spec.scoreBelow,
      `实际 ${report.score}`
    );
  }
  if (spec.scoreAbove !== undefined) {
    check(
      `${name} 分数应不低于 ${spec.scoreAbove}`,
      report.score >= spec.scoreAbove,
      `实际 ${report.score}`
    );
  }
  if (spec.expectLevel) {
    const [id, level] = spec.expectLevel.split('=');
    check(
      `${name} 中 ${id} 应为 ${level}`,
      levelOf(report, id) === level,
      `实际 ${levelOf(report, id) ?? '(未命中)'}`
    );
  }
  return report;
}

// ---------------------------------------------------------------- blacklist

const seeded = HashBlacklist.createWithSeed();
const BLACKLIST = new HashBlacklist();
for (const entry of seeded.all()) {
  BLACKLIST.add(entry);
}

/**
 * EICAR anti-malware test vector.
 *
 * Held in memory rather than read from disk: Windows Defender blocks reads of a
 * file containing this string (verified — even `cp` returns "Permission
 * denied"), so keeping it on the filesystem would make the suite unrunnable on
 * the very host it needs to run on.
 */
const EICAR = new Uint8Array(Buffer.from(
  'X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*',
  'latin1'
));

console.log('='.repeat(72));
console.log('Doc Shield L1 — 扫描器验证');
console.log('='.repeat(72));

// ------------------------------------------------------- 0. digest self-check
const eicarBytes = EICAR;
const eicarNode = crypto.createHash('sha256').update(Buffer.from(eicarBytes)).digest('hex');
const eicarMine = sha256Hex(eicarBytes);
check(
  'SHA-256 实现与 OpenSSL 一致（EICAR 样本）',
  eicarMine === eicarNode,
  `自研 ${eicarMine} / OpenSSL ${eicarNode}`
);

// A few more digests to cover the padding boundaries (55 / 56 / 119 / 120 bytes).
for (const size of [0, 1, 55, 56, 63, 64, 119, 120, 1000]) {
  const blob = new Uint8Array(size);
  for (let i = 0; i < size; i++) {
    blob[i] = (i * 37 + 11) & 0xFF;
  }
  const mine = sha256Hex(blob);
  const reference = crypto.createHash('sha256').update(Buffer.from(blob)).digest('hex');
  check(`SHA-256 边界长度 ${size} 字节`, mine === reference, `${mine} vs ${reference}`);
}

const seedHash = HashBlacklist.seedEntries()[0].sha256;
check(
  '内置黑名单种子哈希与 EICAR 文件一致',
  seedHash === eicarNode,
  `种子 ${seedHash} / 实际 ${eicarNode}`
);

// ------------------------------------------------------------------ 1. clean
scenario('benign.txt', { verdict: 'clean', scoreAbove: 100 });
scenario('benign_notes.md', { verdict: 'clean', scoreAbove: 100 });
scenario('clean.pdf', { mustNotHave: ['pdf.keyword.openaction', 'pdf.keyword.javascript'] });
scenario('normal.zip', {
  mustNotHave: ['archive.bomb-total', 'archive.zip-slip', 'archive.encrypted'],
  verdict: 'clean'
});

// ------------------------------------------------------------ 2. type spoofing
scenario('invoice.pdf', {
  mustHave: ['type.spoof-executable', 'pe.disguised'],
  expectLevel: 'type.spoof-executable=high',
  verdict: 'malicious'
});
scenario('report.pdf.exe', {
  mustHave: ['type.double-extension', 'type.executable-extension'],
  verdict: 'malicious'
});

// -------------------------------------------------------------- 3. credentials
scenario('credential_leak.txt', {
  mustHave: [
    'cred.aws-access-key',
    'cred.stripe-key',
    'cred.github-token',
    'cred.jwt',
    'cred.private-key-block',
    'priv.db-connection',
    'priv.public-ip',
    'priv.china-phone',
    'priv.china-id',
    'priv.server-path',
    'priv.email'
  ]
});
scenario('credential_leak.txt', {
  mustHave: ['ioc.dynamic-dns', 'ioc.paste-service', 'ioc.raw-ip-url']
});

// ------------------------------------------------------------------ 4. script
scenario('malicious.ps1', {
  mustHave: [
    'script.download-exec-combo',
    'script.invoke-expression',
    'script.hidden-window',
    'script.persistence-run-key',
    'script.disable-defender',
    'script.from-base64'
  ],
  verdict: 'malicious'
});

// --------------------------------------------------------------------- 5. PDF
scenario('evil.pdf', {
  mustHave: [
    'pdf.keyword.javascript',
    'pdf.keyword.js',
    'pdf.keyword.openaction',
    'pdf.keyword.aa',
    'pdf.inline-script'
  ]
});

// ----------------------------------------------------------------- 6. archive
scenario('bomb.zip', {
  mustHave: ['archive.bomb-total'],
  expectLevel: 'archive.bomb-total=high'
});
scenario('bomb_ratio.zip', {
  mustHave: ['archive.bomb-ratio'],
  expectLevel: 'archive.bomb-ratio=high'
});
scenario('slip.zip', {
  mustHave: ['archive.zip-slip'],
  expectLevel: 'archive.zip-slip=high',
  verdict: 'malicious'
});
scenario('absolute.zip', { mustHave: ['archive.absolute-path'] });
scenario('sensitive_target.zip', { mustHave: ['archive.sensitive-target'] });
scenario('symlink.zip', { mustHave: ['archive.symlink'] });
scenario('encrypted.zip', {
  mustHave: ['archive.encrypted'],
  expectLevel: 'archive.encrypted=medium'
});
scenario('nested.zip', { mustHave: ['archive.nested-container'] });
scenario('flood.zip', { mustHave: ['archive.entry-flood'] });
scenario('dropper_bundle.zip', {
  mustHave: ['archive.inner-executable', 'pe.behavior.downloader']
});

// ---------------------------------------------------------------------- 7. PE
scenario('dropper.exe', {
  mustHave: [
    'pe.behavior.downloader',
    'pe.behavior.dropper',
    'pe.behavior.persistence'
  ],
  verdict: 'malicious'
});
scenario('injector.exe', {
  mustHave: ['pe.behavior.injection', 'pe.behavior.memory-manipulation'],
  verdict: 'malicious'
});
scenario('backdoor.exe', {
  mustHave: ['pe.behavior.reverse-shell'],
  expectLevel: 'pe.behavior.reverse-shell=high'
});
scenario('keylogger.exe', { mustHave: ['pe.behavior.keylogger'] });
// `pe.encrypted-code-section` is suppressed when a known packer is already
// identified, so only the packer signal is asserted here. The high section
// entropy is verified directly against the parser further down.
scenario('packed.exe', {
  mustHave: ['pe.packer'],
  mustNotHave: ['pe.no-imports']
});
scenario('noimports.exe', {
  mustHave: ['pe.no-imports'],
  expectLevel: 'pe.no-imports=high'
});

// Structural assertions on the PE parser, independent of the report layer.
const dropperAnalysis = analyzePe(load('dropper.exe'));
check('PE 解析成功', dropperAnalysis.valid, dropperAnalysis.error);
check('PE 机器类型为 x86', dropperAnalysis.machine === 0x14C, `0x${dropperAnalysis.machine.toString(16)}`);
check(
  'PE 导入函数数量为 6',
  dropperAnalysis.importedFunctionCount === 6,
  `实际 ${dropperAnalysis.importedFunctionCount}: ${dropperAnalysis.imports
    .map((entry) => `${entry.dll}[${entry.functions.join('|')}]`)
    .join(' ')}`
);
check(
  'PE 导入表被正确解析出 DLL',
  dropperAnalysis.imports.map((entry) => entry.dll).includes('urlmon.dll'),
  dropperAnalysis.imports.map((entry) => entry.dll).join(', ')
);
check(
  'PE 节表被正确解析',
  dropperAnalysis.sections.length === 1 && dropperAnalysis.sections[0].name === '.rdata',
  JSON.stringify(dropperAnalysis.sections)
);
check(
  'PE 入口点位于节内',
  dropperAnalysis.entryPointInsideSection === true
);

const packedAnalysis = analyzePe(load('packed.exe'));
check(
  '加壳样本的代码节熵高于 7.2',
  packedAnalysis.sections[0].entropy > 7.2,
  `实际 ${packedAnalysis.sections[0].entropy.toFixed(3)}`
);

// ------------------------------------------------------------------ 8. macro
scenario('macro.docm', {
  mustHave: [
    'macro.vba-project-present',
    'macro.auto-exec-trigger',
    'macro.host-abuse-api',
    'macro.execution-command'
  ],
  verdict: 'malicious'
});
scenario('legacy_macro.doc', {
  mustHave: ['macro.vba-project-present', 'macro.auto-exec-trigger']
});
scenario('no_macro.docx', {
  mustNotHave: ['macro.vba-project-present', 'macro.vba-project' ]
});

// -------------------------------------------------------------- 9. blacklist
const eicarReport = ThreatScanner.scanFile('eicar_test_file.txt', EICAR, {
  blacklist: BLACKLIST
});
check(
  'EICAR 命中已知样本黑名单',
  ids(eicarReport).includes('signature.blacklist-hit'),
  ids(eicarReport).join(', ') || '(无)'
);
check(
  'EICAR 判定为 malicious',
  eicarReport.verdict === 'malicious',
  eicarReport.verdict
);
check(
  'EICAR 黑名单发现为 high',
  levelOf(eicarReport, 'signature.blacklist-hit') === 'high',
  String(levelOf(eicarReport, 'signature.blacklist-hit'))
);

// 未收录内容不应误报黑名单命中。
const unknownHashReport = ThreatScanner.scanFile('benign.txt', load('benign.txt'), {
  blacklist: BLACKLIST
});
check(
  '未收录文件不产生黑名单命中',
  !ids(unknownHashReport).includes('signature.blacklist-hit'),
  ids(unknownHashReport).join(', ')
);

// --------------------------------------------------------------- 10. perf
const perfStart = Date.now();
const perfReport = ThreatScanner.scanFile('flood.zip', load('flood.zip'), {
  blacklist: BLACKLIST
});
const perfMs = Date.now() - perfStart;
check(
  '12000 条目归档在 3000 ms 内完成扫描',
  perfMs < 3000,
  `实际 ${perfMs} ms（得分 ${perfReport.score}）`
);

// ------------------------------------------- 11. requirement pre-check parity
//
// The on-device pre-check mirrors the server's keyword vocabulary. These cases
// pin the *observable* behaviour of `parse_requirement()`, measured by running
// it directly, so device guidance cannot drift from server behaviour unnoticed.
//
//   text                                                    server parse
//   ------------------------------------------------------  --------------------------------
//   检查文件是否包含敏感信息                                  all fields empty
//   提交论文和相关材料                                        all fields empty
//   提交课程论文 PDF、封面和签字承诺书；文件名使用学号_姓名_课程名称。  formats=[pdf], materials=[封面,课程论文]
//   请提交 PDF 课程论文，正文不少于 3000 字，文件命名：...       formats, materials, naming, length
const hintOf = (text) => precheck(text);

const deviceCase = hintOf('检查文件是否包含敏感信息');
check(
  '与服务器一致：无可识别关键字的要求判为 weak',
  deviceCase.level === 'weak',
  `${deviceCase.level} / tags=${deviceCase.tags.join(',')}`
);

const vagueCase = hintOf('提交论文和相关材料');
check(
  '与服务器一致：泛化表述判为 weak',
  vagueCase.level === 'weak',
  `${vagueCase.level} / tags=${vagueCase.tags.join(',')}`
);

const defaultCase = hintOf(
  '提交课程论文 PDF、封面和签字承诺书；文件名使用学号_姓名_课程名称。'
);
check(
  '默认示例要求可识别 PDF 与材料词',
  defaultCase.level === 'ok'
    && defaultCase.tags.includes('PDF')
    && defaultCase.tags.includes('封面')
    && defaultCase.tags.includes('课程论文'),
  defaultCase.tags.join(',')
);

const explicitCase = hintOf(
  '请提交 PDF 课程论文，正文不少于 3000 字，文件命名：学号_姓名_课程名称，须含封面和参考文献。'
);
check(
  '完整要求可识别格式/材料/命名/篇幅',
  explicitCase.level === 'ok'
    && explicitCase.tags.includes('PDF')
    && explicitCase.tags.includes('正文')
    && explicitCase.tags.includes('参考文献')
    && explicitCase.tags.includes('命名规则')
    && explicitCase.tags.includes('字数/页数'),
  explicitCase.tags.join(',')
);

check('空要求判为 weak', hintOf('   ').level === 'weak', hintOf('   ').level);

check(
  '截止时间可识别',
  hintOf('请于 2026年12月31日 前提交 PDF 报告。').tags.includes('截止时间'),
  hintOf('请于 2026年12月31日 前提交 PDF 报告。').tags.join(',')
);

// Word-boundary guard: ASCII aliases must not fire inside longer words.
check(
  '别名不在更长单词内误命中（doc/docker、md/cmd）',
  !containsAlias('docker image', 'doc') && !containsAlias('cmd.exe', 'md'),
  `doc@docker=${containsAlias('docker image', 'doc')} md@cmd=${containsAlias('cmd.exe', 'md')}`
);
check(
  '独立出现的别名仍能命中',
  containsAlias('submit doc', 'doc') && containsAlias('a .md file', 'md')
    && containsAlias('报告', '报告'),
  'doc/md/报告'
);
check(
  '中文别名不受词边界限制',
  containsAlias('只需一张图片即可', '图片'),
  String(containsAlias('只需一张图片即可', '图片'))
);

// A length marker without a number is not a length rule.
check(
  '缺少数字时不算篇幅要求',
  !hintOf('请提交 PDF 报告，不少于若干字。').tags.includes('字数/页数'),
  hintOf('请提交 PDF 报告，不少于若干字。').tags.join(',')
);
check(
  '仅出现「约」不构成篇幅要求',
  !hintOf('请提交 TXT 说明，约两页即可。').tags.includes('字数/页数'),
  hintOf('请提交 TXT 说明，约两页即可。').tags.join(',')
);

// ------------------------------- 12. requirement contract (naming + formats)
//
// The on-device checker and the server checker must agree on every case in
// platform/contracts/requirement_cases.json. The Python side reads the same file
// (platform/backend/tests/test_requirement_contract.py), so a behaviour change
// on either side fails the other side's tests instead of silently diverging.
const CONTRACT = JSON.parse(
  fs.readFileSync(path.resolve(here, '../../platform/contracts/requirement_cases.json'), 'utf8')
);

const sameSet = (a, b) => {
  const left = [...a].sort();
  const right = [...b].sort();
  return left.length === right.length && left.every((item, i) => item === right[i]);
};

for (const spec of CONTRACT.namingRuleExtract) {
  const actual = extractNamingRule(spec.text);
  check(
    `命名规则抽取：${spec.text.slice(0, 24)}`,
    actual === spec.rule,
    `实际 ${JSON.stringify(actual)} 期望 ${JSON.stringify(spec.rule)}`
  );
}

for (const spec of CONTRACT.namingTemplateParse) {
  const template = parseNamingTemplate(spec.rule);
  check(
    `命名模板解析：${spec.rule}`,
    template.recognised === spec.recognised,
    `recognised=${template.recognised} 期望 ${spec.recognised}`
  );
  if (!spec.recognised) {
    continue;
  }
  check(
    `命名模板分段：${spec.rule}`,
    sameSet(template.kinds, spec.kinds),
    `实际 ${template.kinds.join(',')} 期望 ${spec.kinds.join(',')}`
  );
  check(
    `命名模板分隔符：${spec.rule}`,
    template.separator === spec.separator,
    `实际 ${JSON.stringify(template.separator)} 期望 ${JSON.stringify(spec.separator)}`
  );
  check(
    `命名模板扩展名：${spec.rule}`,
    template.extension === spec.extension,
    `实际 ${JSON.stringify(template.extension)} 期望 ${JSON.stringify(spec.extension)}`
  );
}

for (const spec of CONTRACT.namingCheck) {
  const template = parseNamingTemplate(spec.rule);
  const result = checkNaming(spec.file, template);
  const label = `命名校验：${spec.rule} ← ${spec.file}`;
  if (spec.recognised === false) {
    check(`${label}（规则不可校验，跳过判定）`, result.checked === false, `checked=${result.checked}`);
    continue;
  }
  check(`${label}（应被检查）`, result.checked === true, `checked=${result.checked}`);
  check(
    `${label}（判定 ${spec.ok ? 'pass' : 'fail'}）`,
    result.ok === spec.ok,
    `实际 ok=${result.ok} problems=${result.problems.join(',')}`
  );
  check(
    `${label}（问题码）`,
    sameSet(result.problems, spec.problems),
    `实际 [${result.problems.sort().join(',')}] 期望 [${[...spec.problems].sort().join(',')}]`
  );
}

for (const spec of CONTRACT.formatCheck) {
  const result = checkFormats(spec.formats, spec.files);
  const label = `格式校验：[${spec.formats.join(',')}] ← [${spec.files.join(',')}]`;
  check(`${label}（缺失项）`, sameSet(result.missing, spec.missing),
    `实际 [${result.missing.join(',')}] 期望 [${spec.missing.join(',')}]`);
  check(`${label}（范围外文件）`, sameSet(result.offList, spec.offList),
    `实际 [${result.offList.join(',')}] 期望 [${spec.offList.join(',')}]`);
}

// The bundled sample brief must yield a usable naming template — this is the
// regression that started it: `文件名使用学号_姓名_课程名称` produced no rule
// at all, so the naming check never ran.
const sampleBrief = parseRequirement(
  '提交课程论文 PDF、封面和签字承诺书；文件名使用学号_姓名_课程名称。'
);
check(
  '样例要求能抽出命名模板',
  sampleBrief.namingTemplate.recognised
    && sampleBrief.namingTemplate.kinds.join(',') === 'studentId,name,course',
  JSON.stringify(sampleBrief.namingRule)
);
check(
  '样例要求能抽出格式 pdf',
  sampleBrief.formats.join(',') === 'pdf',
  sampleBrief.formats.join(',')
);

// ------------------------------- 13. requirement audit (device-side findings)
//
// `auditRequirement` turns the contract verdicts into the finding list the page
// renders, and `scoreForFindings` mirrors the server's scoring table. Both run
// with no upload — the audit reads names only. The scoring table is duplicated
// on purpose (`scripts`/server side cannot be shared), so it is asserted here
// against the arithmetic in platform/backend/modules/risk_scoring.py.
const GOOD = '2024001_张三_数据结构.pdf';
const REVERSED = '张三_2024001_数据结构.pdf';

const titles = (audit) => audit.findings.map((finding) => finding.title);

{
  const brief = '提交课程论文 PDF；文件名使用学号_姓名_课程名称。';

  const clean = auditRequirement(brief, [GOOD]);
  check('命名/格式全对时没有 finding', clean.findings.length === 0, titles(clean).join(' | '));
  check(
    '命名/格式全对时有校验说明',
    clean.note.includes('校验了 1 个文件名'),
    clean.note
  );
  check('端内解析回显包含命名模板', clean.echo.includes('命名'), clean.echo);
  check('端内解析回显包含格式', clean.echo.includes('PDF'), clean.echo);

  const bad = auditRequirement(brief, [REVERSED]);
  check('命名段序错误产出 1 条 finding', bad.findings.length === 1, titles(bad).join(' | '));
  check(
    '命名 finding 点名了文件',
    bad.findings[0].title.includes(REVERSED),
    bad.findings[0].title
  );
  check(
    '命名 finding 说明错在哪一段',
    bad.findings[0].evidence.includes('学号') && bad.findings[0].evidence.includes('姓名'),
    bad.findings[0].evidence
  );
  check('命名 finding 为 medium', bad.findings[0].riskLevel === 'medium', bad.findings[0].riskLevel);
  check(
    '命名 finding 建议给出模板',
    bad.findings[0].suggestion.includes('学号_姓名_课程名称'),
    bad.findings[0].suggestion
  );

  // Missing required format, and a file outside the required set, are two
  // separate findings: one is about a gap, the other about a stray file.
  const wrongFormat = auditRequirement(brief, ['2024001_张三_数据结构.png']);
  check(
    '缺格式与格式越界各 1 条 finding',
    wrongFormat.findings.length === 2,
    titles(wrongFormat).join(' | ')
  );
  check(
    '缺格式 finding 用了中文格式名',
    wrongFormat.findings.some((item) => item.title.includes('缺少要求的 PDF 格式材料')),
    titles(wrongFormat).join(' | ')
  );
  check(
    '越界 finding 汇总了文件名',
    wrongFormat.findings.some((item) => item.evidence.includes('2024001_张三_数据结构.png')),
    wrongFormat.findings.map((item) => item.evidence).join(' | ')
  );

  // An unusable rule must be reported, not treated as "every name passed".
  // The rule text deliberately names no format: format keywords are read from
  // the whole brief, including the naming rule, so `只要一张图片` would add a
  // real PNG format finding and mask which check produced what.
  const proseRule = auditRequirement('命名规则：随便写', [GOOD]);
  check('无法解析的命名规则产出 1 条 finding', proseRule.findings.length === 1,
    titles(proseRule).join(' | '));
  check('无法解析的命名规则为 low', proseRule.findings[0].riskLevel === 'low',
    proseRule.findings[0].riskLevel);
  check(
    '无法解析的命名规则说明是人工确认',
    proseRule.findings[0].title.includes('需人工确认'),
    proseRule.findings[0].title
  );

  const empty = auditRequirement('请提交论文和相关材料', [GOOD]);
  check('无可比对条款时不产出 finding', empty.findings.length === 0, titles(empty).join(' | '));
  check('无可比对条款时说明原因', empty.note.includes('没有可端内比对'), empty.note);
}

check('无 finding 时满分为 100', scoreForFindings([]) === 100, String(scoreForFindings([])));
check(
  '1 条 medium 扣 12 分',
  scoreForFindings([{ title: 'a', evidence: '', suggestion: '', riskLevel: 'medium' }]) === 88,
  String(scoreForFindings([{ title: 'a', evidence: '', suggestion: '', riskLevel: 'medium' }]))
);
check(
  '同级别最多计 4 条（与 risk_scoring.py 一致）',
  scoreForFindings(Array.from({ length: 9 }, () => (
    { title: 'a', evidence: '', suggestion: '', riskLevel: 'medium' }
  ))) === 52,
  String(scoreForFindings(Array.from({ length: 9 }, () => (
    { title: 'a', evidence: '', suggestion: '', riskLevel: 'medium' }
  ))))
);
check(
  'low 每条扣 3 分',
  scoreForFindings([
    { title: 'a', evidence: '', suggestion: '', riskLevel: 'low' },
    { title: 'b', evidence: '', suggestion: '', riskLevel: 'low' }
  ]) === 94,
  'expected 94'
);
check(
  'high 每条扣 25 分',
  scoreForFindings([{ title: 'a', evidence: '', suggestion: '', riskLevel: 'high' }]) === 75,
  'expected 75'
);

// The echo is what the attribution card shows; it must never be empty when the
// brief did state something comparable.
{
  const echo = describeLocalRequirements(parseRequirement('提交 PDF；文件名使用学号_姓名。'));
  check('回显包含两段模板', echo.includes('2 段'), echo);
check(
  '不可解析的规则回显为人工确认',
  describeLocalRequirements(parseRequirement('命名规则：随便写')).includes('人工确认'),
  describeLocalRequirements(parseRequirement('命名规则：随便写'))
);
}

// --------------------------------------------------------------- reporting
console.log(`\n通过 ${passed} 项，失败 ${failed} 项`);
if (failures.length > 0) {
  console.log('\n失败明细：');
  for (const line of failures) {
    console.log(`  ✗ ${line}`);
  }
}

// Compact result table so a human can eyeball every fixture.
console.log('\n' + '-'.repeat(72));
console.log(
  '文件'.padEnd(24) + '判定'.padEnd(12) + '分数'.padEnd(7) + '高/中'
);
console.log('-'.repeat(72));

const ALL_FIXTURES = fs.readdirSync(FIXTURES).sort();
for (const fixture of ALL_FIXTURES) {
  const report = ThreatScanner.scanFile(fixture, load(fixture), { blacklist: BLACKLIST });
  const high = report.findings.filter((f) => f.level === 'high').length;
  const medium = report.findings.filter((f) => f.level === 'medium').length;
  console.log(
    fixture.padEnd(24) + report.verdict.padEnd(12) +
    String(report.score).padEnd(7) + `${high}/${medium}`
  );
}

process.exit(failed === 0 ? 0 : 1);
